# Generated by Django 5.2.1 on 2025-05-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('interest_invest', models.CharField(max_length=255)),
                ('interest', models.CharField(max_length=50)),
                ('range_investment', models.CharField(max_length=100)),
                ('expected_roi', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('net_worth', models.CharField(max_length=100)),
                ('last_turnover', models.CharField(max_length=100)),
                ('current_loan_liability', models.CharField(max_length=100)),
                ('last_it_paid', models.CharField(max_length=100)),
                ('fund_looking_for', models.CharField(max_length=100)),
                ('purpose_of_funding', models.TextField()),
                ('nature_of_funding', models.CharField(max_length=255)),
                ('offered_roi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
