# Generated by Django 5.2.1 on 2025-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advisoryapplication_financialservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialservices',
            name='city',
        ),
        migrations.AddField(
            model_name='financialservices',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialservices',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
